[project]
name = "bing-rewards"
dynamic = ["version"]
description = "Perform automated Bing Rewards searches"
license = "MIT"
readme = "README.md"
authors = [
	{ name = "jack-mil", email = "62065280+jack-mil@users.noreply.github.com" },
]

keywords = ["automation", "bing", "search", "pynput", "points", "xbox"]
classifiers = [
	"Programming Language :: Python :: 3 :: Only",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
	"Operating System :: Microsoft :: Windows",
	"Operating System :: POSIX :: Linux",
	"Intended Audience :: End Users/Desktop",
	"Topic :: Utilities",
]
requires-python = ">= 3.10"
dependencies = ["pynput~=1.7"]

[project.urls]
Homepage = "https://github.com/jack-mil/bing-rewards/README.md"
Repository = "https://github.com/jack-mil/bing-rewards"
Issues = "https://github.com/jack-mil/bing-rewards/issues"

[project.optional-dependencies]
dev = ["ruff", "pre-commit"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "UNKNOWN"

[tool.hatch.build.targets.sdist]
exclude = [
	".github/"
]

[project.scripts]
bing-rewards = "bing_rewards:main"


# Tooling config
# -------------

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["C", "E", "F", "W", "B"]
# E203: whitespace before ':'; ignored due to `black` format
# E501: Line too long; Disable in preference of Bugbear B509 (can't be too long, give or take)
# W503: Line break before binary operator; conform to PEP8 as of 2016
ignore = ["E203", "E501", "E226"]
