name: 'Build & Publish'
on:
  push:
    branches: [master, develop]
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build Distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python >= 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.10'
          cache: pip

      - name: Install hatch
        run: pip install -U hatchling hatch-vcs

      - name: Build Project
        run: hatchling build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bing-rewards
          path: dist/

  publish:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    needs:
      - build
    # if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    environment:
      name: testpypi
      url: https://test.pypi.org/p/bing-rewards
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bing-rewards
          path: dist/

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  release:
    name: Create Github Release
    runs-on: ubuntu-latest
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bing-rewards
          path: dist/

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/
